config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'rates#main_page'
  get 'search_rates_by_dates_and_currency', to: 'rates#search_rates_by_dates_and_currency'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rate.rb
# frozen_string_literal: true

class Rate < ApplicationRecord
  validates_uniqueness_of :created_date, scope: :currency

  validates :created_date, presence: true
  validates :currency, presence: true
  validates :exchange_rate, presence: true

  validate :validate_date
  validate :validate_rate

  def validate_date
    condition1 = created_date.is_a?(Integer)
    condition2 = created_date.is_a?(Float)
    errors.add(:created_date, 'it is not a date, it is a number') if condition1 || condition2
  end

  def validate_rate
    condition = 0
    errors.add(:exchange_rate, 'it is not BigDecimal, it is String') if exchange_rate == condition
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rates_controller.rb
# frozen_string_literal: true

class RatesController < ApplicationController
  def main_page
    @quantity_of_records = Rate.count
    @rates = Rate.last(8)
  end

  def search_rates_by_dates_and_currency
    @currency = params['currency']

    start_date = RateHelper.parse_date(params['start_date'])
    end_date = RateHelper.parse_date(params['end_date'])
    range = { created_date: start_date..end_date }
    sorted = Rate.where(range)

    @sorted = sorted.where(currency: @currency)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/rate_helper.rb
# frozen_string_literal: true

module RateHelper
  def self.parse_date(date_params)
    date_params = date_params.transform_values(&:to_i)

    year = date_params['(1i)']
    month = date_params['(2i)']
    day = date_params['(3i)']

    Date.new(year, month, day)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nbkr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rates/index.html.erb
<%= form_tag(search_path, method: :get) do %>
    <%= date_select(:start_date, params[:search]) %><br>
    <%= date_select(:end_date, params[:search]) %><br>
    <%= select_tag 'currency', options_for_select([ 'EUR', 'USD', 'RUB', 'KZT' ]) %><br>
    <%= submit_tag('Search') %>
<% end %>

<h1>NBKR exchange rates</h1>
<table>
  <tr>
    <th>created_date</th>
    <th>currency</th>
    <th>exchange rate</th>
  </tr>

  <% @rates.each do |rate| %>
    <tr>
      <td><%= rate.created_date.strftime('%d.%m.%Y') %></td>
      <td><%= rate.currency %></td>
      <td><%= rate.exchange_rate %></td>
    </tr>
  <% end %>
</table>

app/views/rates/main_page.html.erb
<%= form_tag(search_rates_by_dates_and_currency_path, method: :get) do %>

    <p>Start_date: <%= date_select(:start_date, params[:search]) %></p>
    <p>End_date: <%= date_select(:end_date, params[:search]) %></p>

    <%= select_tag 'currency', options_for_select([ 'EUR', 'USD', 'RUB', 'KZT' ]) %><br>

    <br><%= submit_tag('Search') %>
<% end %>

<h1>NBKR exchange rates</h1>
<h2>Current date: <%= Date.today.strftime('%d.%m.%Y') %> (<%= Date.today.strftime('%A') %>)</h2>
<h4>Total records: <%= @quantity_of_records %></h4>
<h4>last 8 records</h4>

<table>
  <tr>
    <th>created_date</th>
    <th>currency</th>
    <th>exchange rate</th>
  </tr>

  <% @rates.each do |rate| %>
    <tr>
      <td><%= rate.created_date.strftime('%d.%m.%Y') %></td>
      <td><%= rate.currency %></td>
      <td><%= rate.exchange_rate %></td>
    </tr>
  <% end %>
</table>

app/views/rates/search.html.erb
<h1>For <%= @currency %></h1>
<table>
  <tr>
    <th>created_date</th>
    <th>currency</th>
    <th>exchange rate</th>
  </tr>

  <% @sorted.each do |rate| %>
    <tr>
      <td><%= rate.created_date.strftime('%d.%m.%Y') %></td>
      <td><%= rate.currency %></td>
      <td><%= rate.exchange_rate %></td>
    </tr>
  <% end %>
</table>
<%= line_chart @sorted.group(:created_date).sum(:exchange_rate), id: "users-chart", width: "800px", height: "500px" %>

app/views/rates/search_rates_by_dates_and_currency.html.erb
<h1>For <%= @currency %></h1>
<%= link_to "Go back", root_path %><br>

<table>
  <tr>
    <th>created_date</th>
    <th>currency</th>
    <th>exchange rate</th>
  </tr>

  <% @sorted.each do |rate| %>
    <tr>
      <td><%= rate.created_date.strftime('%d.%m.%Y') %></td>
      <td><%= rate.currency %></td>
      <td><%= rate.exchange_rate %></td>
    </tr>
  <% end %>
</table>

<%= line_chart @sorted.group(:created_date).sum(:exchange_rate), id: "users-chart", width: "800px", height: "500px" %>